### ISSUE TITLE
Add ElectricPowerUsageSummary blocks

### ISSUE THREAD

**Issue by peter279k** [peter279k/green-button-converter#8]
As title, we also consider adding this `ElectricPowerUsageSummary` blocks for customers to know their billing of power usage.

**Comment by dfcoffin** [comment]
The latest version of the NAESB REQ.21 ESPI standard has [DEPRECATED] the ElectricPowerUsageSummary which has been replaced by the UsageSummary resource.  The new resource contains the same attributes with additional information found in the ElectricPowerUsageSummary, but the name better reflects the standards ability to support electricity, natural gas, and water.

**Comment by peter279k** [comment]
Closed via PR #17.
